from ado.ado_abx import ADOClient, Project, GitRepo, Environment, KubernetesResource, ServiceEndpoint
from ado import ado_abx


_client = ADOClient(organisation_url='http://azuredevops.ad.home.local/DefaultCollection', access_token='e4t7gerblbfziblu4y7lzdjccvsmkdnzehymnczbz4odctb6rzuq')

_project = Project()
_project.Name = "test19"
_project.Description = "my test18 project"
#_response = _client.getProjectList()
#_response = _client.getProjectList_dict()
#_response = _client.getProject('alpha')
#_response = _client.createProject(_project)
#_response = _client.deleteProject("beta")

_repo = GitRepo()
_repo.Name = "myrepo1"
_repo.ProjectId = "test"   
#_response = _client.getRepositoryList("test")
#_response = _client.getRepository('test', 'test')
#_response = _client.createRepository(_repo)


_envinronment = Environment()
_envinronment.Name = "env11"
_envinronment.Description = "the desciption"
_envinronment.ProjectId = 'alpha'
#_response = _client.getEnvironmentList("alpha")
#_response = _client.getEnvironment("alpha", 'env1')
#_response = _client.createEnvironment(_envinronment)


_k8sep = KubernetesResource()
_k8sep.ProjectId = 'alpha'
_k8sep.EnvironmentId = 'env1'
_k8sep.Name = 'test1'
_k8sep.Namespace = 'alpha'
_k8sep.ClusterName = 'tap1' 
_k8sep.ServiceEndpointId = '38e4c67f-d96e-4a20-b6f9-6c82a5f110dd'

#_response = _client.getResourceList('alpha', 1)
#_response = _client.getKubernetesResource('alpha', 'env1', 'alpha')
#_response = _client.getServiceEndpointList('alpha')
#_response = _client.createKubernetesResource(_k8sep)

_sep = ServiceEndpoint()
_sep.Name = 'tap3'
_sep.ProjectId = 'beta'
_sep.Type = 'kubernetes'
_sep.Url = 'https://192.168.41.69:6443'
_sep.ApiToken = "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklucFNMWFZITlhBelZuYzBjbmxOUVU5bFJFMXVNMGhGZUVkWFMwUk5VMWh1U0RCSFpYTTJVMnhwVnpnaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKMGIydGxiaTFoWkcxcGJpSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSjBiMnRsYmkxaFpHMXBiaUlzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJamxpT1RBeU5tRXpMV0ZrWldFdE5EWmtZaTA0TWpjNUxUUTJPRFE1TkRZek9URmhaaUlzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwcmRXSmxMWE41YzNSbGJUcDBiMnRsYmkxaFpHMXBiaUo5LkI1MnpReV83UTFZNG5NYk5RQWoycVoxa0hfUHA5ZjVNbnNjZkFIRWltVnJXQXNCRmxXUzVWZFVHVnFVYXlBR0lZRFJ5MENCcXdlUzF0MWFmVVVmSGh3NWFlZThJaW9uZDloektkV1lheUJUVHV0QVh0TGw0WWpvN08wTENkSmhxaDhxUDJyOUQ5LXRjQnZJVGd0eXVUS0ZrOHVsUlBQVGlTZ0Ryek4xQk1rMXp6Sk9jcjhWUTZFTXdSX3FuVFFyZU8yenlXZGFMZkkwODE4cjlIaEt2dmNUOWpidW93WTQ3aEFXNjRRY1liMGtscm5POHNfblJFQXhFV3UyMDBoSGtzcUNEMTNRYmEySTRHbnpHbEpWb3VIVmxmc09RUThMYzJiVDRjem1YS28xMWl5YVBuamxGdklEdGE3bDRlVnBuYktWc3V0QUpBSkNpdUZDWElsb0EwQQ=="
_sep.Certificate = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1EY3dNakE0TkRnME1Gb1hEVE0wTURZek1EQTROVE0wTUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDVvCnZ6cGJXUkFlOXU0THlhL1Jyd2xDc29jeTZWREE4a1lzdFY1bUtid1dnQUQzQTdmbFBUa1RabC9CL0xWc0d5RG0KMGJGSkRDZUVjbDErSURQVVVOelhpUld3QWw4WHZRQkhLUTJ6TWdqS3gyZ3ltVkdnL3lteGFpRkFRVTNHZHZUZApWV0NtT1Q1STFmaUtpMWd2bTg1SDJZaUx4aGRQc3RjcExnRUs3SStSSGlqUjJkQlFHaFJ5NEJCWXpsTkx6WmswCkZqYzdVU1EvNFBieXBLK2VmVzF0ZE1hV3lJQ3g4cFNMdnhDM3FWWkRhdjZiQ3hPejJCdmE3Y2lZUjFYWUtrSHUKWHhBM1VPUFJlUzdGM2haK3d0d1Vtb1pjMTg4VGNrOXNHVjZ6QzZaamVmT2hUTmYrc21zSndYeWJzVVlzUVhpTwphQmtLdjZ6dWUyS2Eyb3ZmZ2IwQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGT2pzVTBzcnJ5Q2RMa2RKODRORkFlcXZ4UHdDTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQWRodzhWUWtLY0RGQUlMODExeldwWGdFdXVpWHllRjRxTHlsa0s1ZDFWdWJzeQpENnpNc1piSitWamcwdG5HZysvVkJkUEJRbGFnclNkUmsxOTdpN1Q4UHFDTVBiaWdUVjEwdnlEcFV5cGxpZEZQCjMzWkliQ0cwRGlxT0I5TnIrci8wb2k4dzZoSXFuSWt5NzlLSzU4dDNycG1CNm9sRVZlUW1kZGtRUmtsbVRCY2wKYUJIWDlqOEdRR1lmOUJxN1V2R053K2psR3Y4SW9QQUVHd2JGU2ppb2ptU2FvNUJPbHRnNEc1R2swSjdjVUpyVwpWeEp3dFkzTHVXYjZuQnVOOG5LcG5YM0hEa3JXQ1pBQXRFS2Jkd2FlM1l0c2E0Mk5NZktZTFNLcjZ2N1RJTGdSCjM4THBKYlRJWUpuaXVsRm9pZTNaQ0tHZ1Z1elRackhYdGxxeTRnTnUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
#_response = _client.createServiceEndpoint(_sep)

#inputs = {'action':'project-create',"name":"foxtrot","description":"test","visibility":"private","sourcecontroltype":"Git","processtemplate":"6b724908-ef14-45cf-84f8-768b5384da45"}
#inputs = {'action':'project-delete','name':'igloo'}
#inputs = {'action':'endpoint-get',"project":"alpha","name":"env1-alpha-1718601633414"}
#inputs = {'action':'endpoint-list',"project":"alpha"}
#inputs = {'action':'endpoint-list'}
#inputs = {'action':'environment-list',"project":"alpha"}
inputs = {'action':'environment-list'}
#inputs = {'action':'endpoint-get',"project":"beta","name":"tap4"}

#inputs = {"action":"endpoint-create","name":"tap3","project":"beta","type":"kubernetes","apiurl":"https://192.168.41.69:6443","token":"ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklucFNMWFZITlhBelZuYzBjbmxOUVU5bFJFMXVNMGhGZUVkWFMwUk5VMWh1U0RCSFpYTTJVMnhwVnpnaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKMGIydGxiaTFoWkcxcGJpSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSjBiMnRsYmkxaFpHMXBiaUlzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJamxpT1RBeU5tRXpMV0ZrWldFdE5EWmtZaTA0TWpjNUxUUTJPRFE1TkRZek9URmhaaUlzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwcmRXSmxMWE41YzNSbGJUcDBiMnRsYmkxaFpHMXBiaUo5LkI1MnpReV83UTFZNG5NYk5RQWoycVoxa0hfUHA5ZjVNbnNjZkFIRWltVnJXQXNCRmxXUzVWZFVHVnFVYXlBR0lZRFJ5MENCcXdlUzF0MWFmVVVmSGh3NWFlZThJaW9uZDloektkV1lheUJUVHV0QVh0TGw0WWpvN08wTENkSmhxaDhxUDJyOUQ5LXRjQnZJVGd0eXVUS0ZrOHVsUlBQVGlTZ0Ryek4xQk1rMXp6Sk9jcjhWUTZFTXdSX3FuVFFyZU8yenlXZGFMZkkwODE4cjlIaEt2dmNUOWpidW93WTQ3aEFXNjRRY1liMGtscm5POHNfblJFQXhFV3UyMDBoSGtzcUNEMTNRYmEySTRHbnpHbEpWb3VIVmxmc09RUThMYzJiVDRjem1YS28xMWl5YVBuamxGdklEdGE3bDRlVnBuYktWc3V0QUpBSkNpdUZDWElsb0EwQQ==","certificate":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1EY3dNakE0TkRnME1Gb1hEVE0wTURZek1EQTROVE0wTUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDVvCnZ6cGJXUkFlOXU0THlhL1Jyd2xDc29jeTZWREE4a1lzdFY1bUtid1dnQUQzQTdmbFBUa1RabC9CL0xWc0d5RG0KMGJGSkRDZUVjbDErSURQVVVOelhpUld3QWw4WHZRQkhLUTJ6TWdqS3gyZ3ltVkdnL3lteGFpRkFRVTNHZHZUZApWV0NtT1Q1STFmaUtpMWd2bTg1SDJZaUx4aGRQc3RjcExnRUs3SStSSGlqUjJkQlFHaFJ5NEJCWXpsTkx6WmswCkZqYzdVU1EvNFBieXBLK2VmVzF0ZE1hV3lJQ3g4cFNMdnhDM3FWWkRhdjZiQ3hPejJCdmE3Y2lZUjFYWUtrSHUKWHhBM1VPUFJlUzdGM2haK3d0d1Vtb1pjMTg4VGNrOXNHVjZ6QzZaamVmT2hUTmYrc21zSndYeWJzVVlzUVhpTwphQmtLdjZ6dWUyS2Eyb3ZmZ2IwQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGT2pzVTBzcnJ5Q2RMa2RKODRORkFlcXZ4UHdDTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQWRodzhWUWtLY0RGQUlMODExeldwWGdFdXVpWHllRjRxTHlsa0s1ZDFWdWJzeQpENnpNc1piSitWamcwdG5HZysvVkJkUEJRbGFnclNkUmsxOTdpN1Q4UHFDTVBiaWdUVjEwdnlEcFV5cGxpZEZQCjMzWkliQ0cwRGlxT0I5TnIrci8wb2k4dzZoSXFuSWt5NzlLSzU4dDNycG1CNm9sRVZlUW1kZGtRUmtsbVRCY2wKYUJIWDlqOEdRR1lmOUJxN1V2R053K2psR3Y4SW9QQUVHd2JGU2ppb2ptU2FvNUJPbHRnNEc1R2swSjdjVUpyVwpWeEp3dFkzTHVXYjZuQnVOOG5LcG5YM0hEa3JXQ1pBQXRFS2Jkd2FlM1l0c2E0Mk5NZktZTFNLcjZ2N1RJTGdSCjM4THBKYlRJWUpuaXVsRm9pZTNaQ0tHZ1Z1elRackhYdGxxeTRnTnUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="}
#inputs = {'action':'endpoint-delete',"project":"beta","name":"tap3"}

_response = ado_abx.handler('', inputs)


print(_response)
_client = None
